# Generated by Django 5.1.6 on 2025-02-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0, verbose_name='掲載No')),
                ('name', models.CharField(max_length=62, verbose_name='画像名')),
                ('image', models.ImageField(upload_to='images/top_image/', verbose_name='トップ画像')),
                ('init_image', models.ImageField(upload_to='images/top_init_image', verbose_name='トップ画像(小)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
            ],
            options={
                'verbose_name_plural': 'トップページ用画像',
            },
        ),
    ]
